
-- START TRANSACTION;

ALTER SESSION SET CURRENT_SCHEMA = HUMAN_RESOURCES_TEST;

-- truncate table PERSON;
-- truncate table DEPARTMENT;
-- truncate table EMPLOYMENT;

INSERT INTO "PERSON" (FIRST_NAME,LAST_NAME,CUIL)
    VALUES ('Daniel', 'Mora', '252525252525');
INSERT INTO "PERSON" (FIRST_NAME,LAST_NAME,CUIL)
    VALUES ('Homer', 'Simpson', '3333333333');

INSERT INTO "EMPLOYMENT" VALUES ('1', '1', '1', 'edddddd');
INSERT INTO "EMPLOYMENT" VALUES ('2', '2', '2', 'rfrfrfrfr');
